<HTML><HEAD><TITLE>Neue Datei oder neues Verzeichnis anlegen</TITLE></HEAD>
<BODY><A NAME="top">
<BR><FONT COLOR=teal>Neue Datei oder neues Verzeichnis anlegen</FONT>
<HR noshade color="silver">
<A HREF="main.htm">Zurck zur šbersicht</A>
<HR noshade color="silver"><PRE><FONT COLOR="maroon">Schnellkurs</FONT>

1. Taste m : neue Datei anlegen.
2. Taste F7: neues Verzeichnis anlegen.<HR

noshade color="silver"><FONT COLOR="maroon">Beschreibung</FONT> 

Mit Taste m legen Sie eine neue leere Datei an, die Sie mit einem 
beliebigen Programm weiterverarbeiten k”nnen.

Mit F7 hingegen wird ein neues leeres Unterverzeichnis erstellt.

Dateien und Verzeichnisse drfen nicht den gleichen Namen tragen, wenn sie
sich beide im gleichen Unterverzeichnis befinden. Falls Sie von vom Comander
eine derartige Fehlermeldung erhalten, mssen Sie dem zu erstellenden Objekt
einen anderen Namen oder wenigstens eine andere Dateiendung geben.

Sie k”nnen brigens auch Verzeichnisse mit einer Endung versehen. Ein
Verzeichnis TEST.XXX ist durchaus erlaubt. Ihre Eingabe k”nnen Sie wie Text
editieren (Einfgen, šberschreiben, L”schen usw.). Mit Esc brechen Sie
das Erstellen einer Datei oder eines Verzeichnisses ab.

Viele Anwenderprogramme und auch „ltere DOS-Versionen haben Schwierigkeiten
mit deutschen Umlauten in Dateinamen. Der Comander „ndert daher eingegebene
Umlaute in die entsprechenden Buchstaben ohne Pnktchen um. Desweiteren
werden s„mtliche unerlaubten Sonderzeichen und Leerstellen in Rauten (#)
umgewandelt.

Wenn Sie dennoch Umlaute im Dateinamen haben m”chten, benennen Sie die Datei
per DOS-Befehl um:

rename anderung.txt „nderung.txt

Falls Makefile beim Anlegen einer Leerdatei eine bereits vorhandene Datei
gleichen Namens entdeckt, wird eine Warnung ausgegeben. Wenn Sie die
vorhandene Datei dann von Makefile berschreiben lassen, sind die darin
enthaltenen Daten unwiderruflich weg.</PRE>
<HR noshade color="silver">
<A HREF="#top"> Zurck zum Anfang</A>
</BODY></HTML>
