@echo off
help %1
Goto ENDE

Die ist die Startdatei fÅr die Syntaxhilfe fÅr den Editor ED.EXE. DOSHELP.BAT
mu· sich immer im gleichen Verzeichnis wie ED.EXE befinden. Die aufzurufende
Hilfe kann sich in jedem beliebigen Verzeichnis befinden - ggf. mu· der
vollstÑndige Pfad als Startbefehl eingegeben werden. Somit kînnen Sie sich 
Ihre BATCH-Hilfe auch selbst programmieren - als BATCH-Datei z.B. Ferner kann
DOSHELP.BAT auch durch ein Programm mit dem Namen DOSHELP.EXE oder 
DOSHELP.COM ersetzt werden.

:ENDE
