
@ECHO OFF
ECHO.
ECHO Um mit einem DoubleSpace- oder DriveSpace-Laufwerk zu arbeiten,
ECHO mÅssen Sie das Programm "DriveSpace" unter Windows 95 starten.
ECHO.
ECHO    So starten Sie das Programm "DriveSpace":
ECHO.
ECHO    1. Starten Sie Windows 95.
ECHO    2. WÑhlen Sie aus dem MenÅ "Start" den Befehl "AusfÅhren".
ECHO    3. Geben Sie in das Textfeld folgendes ein:
ECHO.
ECHO          drvspace
ECHO.
ECHO    4. Klicken Sie auf "OK".
ECHO.

