PROGRAM Type;

{zeigt den Aufbau eines einfachen Textbetrachters}



PROCEDURE FilePos;
BEGIN
  If (@FSizeOut=0) Then Exit;                     {wegen Division durch Null}
  @b:= @div (@mul (@FPosOut, 100), @FSizeOut);
  Window (1, 1, 80, 2);
  If (@b<100) Then GotoXY (76, 1) Else GotoXY (75, 1);
  Write (@b, ' %');
END;
{erzeugt rechtsbndige Prozentanzeige fr die Dateiposition}



PROCEDURE Hilfetext;
BEGIN
  WriteLn;
  WriteLn ('TYPE  Textbetrachter');
  WriteLn ('Syntax: TYPE [Dateiname]');
  Halt;
END;
{Gibt einen Hinweistext aus, wenn kein Parameter oder /? eingegeben wurde}



PROCEDURE Stop;
BEGIN
  WriteLn;
  WriteLn (!a);
  WriteLn ('Datei konnte nicht ge”ffnet werden.', #7);
  Halt;
END;
{Gibt eine Fehlermeldung aus}



PROCEDURE ReadFileName;
BEGIN
  Init;
  WriteLn ('Welche Datei soll angezeigt werden ?', #13#10);
  Write   ('Ihre Eingabe : ');
  ReadLn (!a);
  !a:= !UpString(!a);
END;
{Zeigt eine Eingabezeile, falls kein Parameter angegeben wurde}



PROCEDURE NewScreen;
BEGIN
  call FilePos
  GetKey;
  Window (1, 3, 80, 23);
  ClrScr;
  Window (1, 3, 80, 24);
END;
{wartet auf Tastendruck, wenn der Bildschirm mit Zeichen gefllt ist.}



FUNCTION FileName;
BEGIN
  FSplit (!a, !b, !c, !d);
  !Result:= !Concat (!c, !d);    {in !b befindet sich der Verzeichnispfad}
END;
{Schneidet vom Dateinamen die Pfadbezeichnung ab}



PROCEDURE FirstScreen;
BEGIN
  Init;
  WriteLn ('Datei: ', &FileName)
  GotoXY (33, 1);
  WriteLn ('Gr”áe: ', @FSizeOut, ' Byte');
  Line (#196);
  GotoXY (1, 24);
  Line (#196);
  Write ('Weiter mit ENTER');
  GotoXY (65, 25);
  Write ('Beenden mit Esc');  ;
  Window (1, 3, 80, 24);
  CursorOff;
END;
{Richtet den Bildschirm ein}


{----------------------------- Hauptprogramm --------------------------------}

BEGIN-MAIN
  !a:= !UpString(!ParamStr (1));
  If (!a = '/?')        Then call Hilfetext;
  If (@ParamCount = 0)  Then call ReadFileName;

  OpenOutFile (!a); If (@Error<>0) Then call Stop;

  Call FirstScreen;

  #key:= #0;

  While (not @EoFOut) and (#key<>#Esc) and (@Error=0) Do
  BEGIN
    ReadOutFile (!f);
    WriteLn (!f);
    If (@WhereY=21) Then Call NewScreen;
  ENDW;

  If (#key<>#Esc) Then
  BEGIN
    call FilePos;
    GetKey;
  ENDIF;

  CloseOutFile;
  Init;
END.

{------------------------- Programm-Ende ----------------------------------}