:SSFR
as b beep
as p go
cls
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
01
echo                          +=======================:-:=:X:
09
echo                          #          SSFR Radio         #
03 
echo                          #                             #
11
echo                          # 1...             Super beep #
10
echo                          # 2...              Mega piep #
02
echo                          # 3...                   high #
13
echo                          # 4...             sleepyhead #
05
echo                          # 5...               heathens #
01
echo                          # 6...                   trap #
09
echo                          +=============================+
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
Choice /c:x-123456789 /n /s
if errorlevel 9 goto 7
if errorlevel 8 goto 6
if errorlevel 7 goto 5
if errorlevel 6 goto 4
if errorlevel 5 goto 3
if errorlevel 4 goto 2
if errorlevel 3 goto 1
if errorlevel 2 dumm
if errorlevel 1 goto ex
goto ssfr
:1
LH D:\Musik\BAT\SSFR\SB.BAT
goto ssfr
:2
LH D:\Musik\BAT\SSFR\MP.BAT
goto ssfr
:3
LH D:\Musik\BAT\song.bat
goto ssfr
:4
LH D:\Musik\BAT\song2.bat
goto ssfr
:5
LH D:\Musik\BAT\song3.bat
goto ssfr
:6
LH D:\Musik\BAT\bass.bat
goto ssfr
:7
goto ssfr
:8
goto ssfr
:9
goto ssfr
:ex
color 0 0
cls
gruen
cls
echo #OhrenKrebs
echo #EpilepsieKranker
echo #PenetrationInDenAnusLOL
echo #ICHBINDUMMUNDHOBBYLOSHAHAHAHAHAAHHAAHAHAHAHAH 