@echo off
color 15 1
cls
echo.
echo                                     TrollDOS                                   
echo.
echo         *  An error in your system files is occurred. (error in file)
echo            The File "LDESK" can't run the Desktop file in config.
echo.
echo         *  More details in file:    
echo                  LH %desk%                                                       
echo.
echo         *  Anwser of latest comand in file: File not found! Error 404
echo         *  Please check your config and fix it to load your desktop.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
echo.
beep
pause > NUL
color 7 0
cls