rem + + + Das ist das Herz von TrollDOS. Alles einstallbar. + + +
rem path - - - Nicht verändern!
rem rest krizel ´loolo 4dos fffffICKEN grüße gehen raus an spaceplanet und poisonpotato (flab) (corefile) (ARHUT LOLL)

set go=

:boot
goto %go%
@echo off
color 14 0
cls
echo F-777 DOSBOX BIOS
echo Bios Version : F-777 v.2.0
echo Bios Copyright All Copyrights to ART2PLANETS
echo WELCOME TO TROLLDOS U FUCKING LOOSER XD
color 7 0
@echo on
beep 860 5

call c:\system\runonce\fstrun.bat
call c:\system\runonce\runonce.bat
del c:\system\runonce\fstrun.bat
del c:\system\runonce\runonce.bat


goto %2
:--full
echo load drive C:
c:
echo load sets
rem set - - - Nicht alle einstallbar! - - -
set Path=Z:\;C:\;System\4DOS\;C:\System\PCDOS\;C:\System\MSDOS\;C:\System\PTSDOS\;C:\;C:\System\XCONFIG\;Z:\;C:\System\Treiber\Grafik;C:\System\Treiber\NNANSI;C:\System\Treiber\Grafik;CDRomDrv;C:\System\Treiber\Mouse;C:\System\Treiber\Sound;C:\Programs\bat;C:\SYSTEM\NEWDOS\;C:\Programs\MEMDOS;c:\system\bs\;C:\System\xconfig\boot\;C:\System\xconfig\visual\;c:\system\treiber\sound\;
echo system sets
set PROMPT=$P$G
set COMSPEC=C:\SYSTEM\4DOS\4DOS.COM
SET windir=C:\SYSTEM\XCONFIG\
SET winbootdir=C:\SYSTEM\XCONFIG\
rem sound sets
echo load sound sets
SET SOUND=C:\SYSTEM\TREIBER\SOUND\SB
Set SNDSCAPE=C:\SYSTEM\TREIBER\SOUND\SB
Set Blaster=a220 i5 d1 t4
Set SndScape=C:\SYSTEM\TREIBER\SOUND\SB
SET MIDI=SYNTH:1 MAP:E
rem path sets
echo load path sets (to find programs etc.)
set xpath=C:\System\XCONFIG
set Treiber=C:\System\Treiber
set Programs=C:\Programs
set BAT=C:\Programs\BAT\ 
set Music=D:\Musik
set Emulator=D:\Emulator
set Emulatoren=D:\Emulator
set Games=D:\Games
set Spiele=D:\Games
set Demo=D:\Demos
set Demos=D:\Demos
set Temp=C:\Temp
set TMP=C:\Temp
set Temp4DOS=C:\Temp
set tmp4dos=C:\Temp
set System=C:\System
set systemdrive=C:\
set Visual=C:\System\Xconfig\visual
rem Programme
echo load more sets.
set editor=aurora
set explorer=norton_commander
set player=cubic
set dir=maxdir
alias dir maxdir
set av=Nod32
set ldesk=DLoad
set desk=desk
set dcolor=gruen
set tcolor=cyan
set ncolor=grau
set log=c:\logs
set logs=c:\logs
set dmf=d:\musik\dmf
set reload=auto
set 4file=C:\SYSTEM\4DOS\4DOS.COM
set username=Alphapopo
set userpath=D:
set
echo loading files
rem Treiber (Nicht verendern!!!)
C:\System\4DOS\KStack.com
C:\System\MSDOS\KBD.COM
C:\System\Treiber\Grafik\S3VBE20.Exe /Install
C:\System\Treiber\Grafik\pvga1a.exe
C:\System\Treiber\NNANSI\NNANSI.COM
C:\System\Treiber\Grafik\ET4000.com
c:\system\msdos\smartdrv.exe
c:\system\msdos\pentium1.com
c:\system\msdos\bitdisk
c:\system\msdos\ems
c:\system\msdos\mem
c:\system\msdos\fcbs
c:\system\msdos\files
c:\system\msdos\xsm
c:\system\msdos\modelist
c:\system\msdos\rivafix
c:\system\msdos\umbfill
c:\system\msdos\capslock
c:\system\msdos\sys.com
C:\SYSTEM\MSDOS\KeySpeed 0 0
C:\SYSTEM\TREIBER\mouse\MOUSE.EXE
clock
:--alias
:--as
:--asreload
echo load aliases 
rem hier sind alle + + + aliases + + + 
alias as alias
alias us unalias
as maxdir C:\Programs\bat\mxdr.bat
as wait c:\programs\bat\wait.bat
as load lh
as temp set temp %1
as tmp set tmp %1
as 4dostemp set 4dostemp %1
as 4dostmp set 4dostmp %1
as comspec set comspec %1
as sys sysedit.bat
as system sysedit.bat
as Aurora C:\PROGRAMS\AURORA\AURORA.EXE
as Norton_Commander C:\PROGRAMS\NORTON\NC.EXE
as Norton C:\PROGRAMS\NORTON\NC.EXE
as Mdir C:\PROGRAMS\Mdir\Mdir.EXE
as run lh 
as Anrivirus C:\PROGRAMS\NOD32\Nod32.EXE
as Cubic C:\PROGRAMS\Cubic\Cp.EXE
as Musik C:\PROGRAMS\Cubic\cp.EXE
as Nod32 C:\PROGRAMS\NOD32\Nod32.EXE
as pedit C:\programs\pedit\pedit.exe
as neustart reboot
as sys sysedit.bat
as Programs cdd C:\Programs
as treiber cdd C:\System\Treiber\
as neustart reboot
as rb reboot
as blau color 1 0
as gruen color 2 0
as cd cdd
as cyan color 3 0
as rot color 4 0
as lila color 5 0 
as orange color 6 0 
as grau color 7 0
as dunkelgrau color 8 0
as hellblau color 9 0
as hellgruen color 10 0
as hellrot color 11 0
as pink color 12 0
as hell color 13 0
as gelb color 14 0
as weiss color 15 0
as system sysedit
as programs cdd C:\PROGRAMS
as Color01 color 1 0
as Color02 color 2 0
as Color03 color 3 0
as Color04 color 4 0
as Color05 color 5 0
as Color06 color 6 0
as Color07 color 7 0
as Color08 color 8 0
as Color09 color 9 0
as Color10 color 10 0
as Color11 color 311 0
as Color12 color 12 0
as Color13 color 13 0
as Color14 color 14 0
as color15 color 15 0
as Color15 color 15 0
as 01 color 1 0
as 02 color 2 0
as 03 color 3 0
as 04 color 4 0
as 05 color 5 0
as 06 color 6 0
as 07 color 7 0
as 08 color 8 0
as 09 color 9 0
as 10 color 10 0
as 11 color 11 0
as 12 color 12 0
as 13 color 13 0
as 14 color 14 0
as 15 color 15 0
as version XVERSION.BAT
as lconfig config
as loadconfig config
as lconf config                    
as explorer norton 
as music cdd D:\musik
as reb reboot
as minireboot config.bat
as minireb config.bat
as bat cdd C:\programs\bat
as srt C:\programs\bat\srt.bat
as stress C:\programs\bat\srt.bat
as real C:\demos\real\real.bat
as 2nd_real C:\demos\2nd_real\start.bat
as piep piep.bat
as nerven piep.bat
as editor aurora
as dumm piep.bat
as mr config.bat
as edit Aurora
as FreeEdit FreeEdit.bat
as create edit %1
as SRT_2.0 srt2
as bs cdd c:\system\bs\
as Stress_2 srt2
as attrib c:\programs\bat\at.bat
as editor edit
as dcolor %DCOLOR%
as tcolor %TCOLOR%
as ncolor %NCOLOR%
as spin ti.exe
as ver xversion
as bios c:\system\msdos\black.exe
as umb c:\system\msdos\test!umb
as tasklist mi /c
as list mi /c

goto %1
:--desk
:--d
LH %ldesk%
if not exist lh c:\system\bs\ldnf.bat
:--nodesk
:--outp
:--output
:--novisual
outp

:go