@echo off
clock /x
echo ###############################################################################
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                          System is rebooting. . .                           #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo #                                                                             #
echo ###############################################################################
reboot