@echo off
color 3 0
cls
echo.

color 2 0

echo                   44   44      DDDDD        OOO       SSSS
color 10 0 
echo                   44   44      DD   DD    OO   OO    SS
echo                   4444444      DD   DD    OO   OO     SSSS
color 11 0
echo                        44      DD   DD    OO   OO        SS
echo                        44      DDDDD        OOO       SSSS
echo.
color 3 0
cls
color 2 0

echo                   44   44      DDDDD        OOO       SSSS
color 10 0 
echo                   44   44      DD   DD    OO   OO    SS
echo                   4444444      DD   DD    OO   OO     SSSS
color 11 0
echo                        44      DD   DD    OO   OO        SS
echo                        44      DDDDD        OOO       SSSS
echo.
tcolor